In [14]:
import pandas as pd
import numpy as np

In [15]:
tarifas = pd.read_csv('TARIFAS_ACUEDUCTO_Y_ALCANTARILLADO_2021_20250523.csv')
tarifas
#Linea de codigo para visualización de los datos

,CIUDAD,PERIODO,SERVICIO,SECTOR RESIDENCIAL,CARGO FIJO,CARGO POR CONSUMO 0-16,CARGO POR CONSUMO >-17,TIPO DE TASA,TASA 0-16,TASA >-17
0,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,BAJO - BAJO,7139.92,1390.47,2139.18,Tasa de Uso,2.29,3.52
1,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,BAJO,7139.92,1604.39,2139.18,Tasa de Uso,2.64,3.52
2,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,MEDIO - BAJO,7139.92,2032.22,2139.18,Tasa de Uso,3.34,3.52
3,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,MEDIO,7139.92,2139.18,2139.18,Tasa de Uso,3.52,3.52
4,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,MEDIO - ALTO,10709.88,3208.77,3208.77,Tasa de Uso,5.28,5.28
5,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,ALTO,11423.87,3422.69,3422.69,Tasa de Uso,5.63,5.63
6,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,COMERCIAL,10709.88,3208.77,3208.77,Tasa de Uso,3.52,3.52
7,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,OFICIAL,7139.92,2139.18,2139.18,Tasa de Uso,5.28,5.28
8,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,INDUSTRIAL,9281.90,2780.93,2780.93,Tasa de Uso,4.58,4.58
9,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,ESPECIAL*,7139.92,2139.18,2139.18,Tasa de Uso,0.00,0.00
10,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,BAJO - BAJO,2199.10,658.87,2139.18,Tasa de Uso,1.08,3.52
11,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,BAJO,4398.19,1317.73,2139.18,Tasa de Uso,2.17,3.52
12,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,MEDIO - BAJO,6233.42,1867.59,2139.28,Tasa de Uso,3.07,3.52
13,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,MEDIO,7139.92,2139.18,2139.18,Tasa de Uso,3.52,3.52
14,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,MEDIO - ALTO,11331.05,3394.88,3394.88,Tasa de Uso,5.59,5.59
15,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,ALTO,12087.88,3621.63,3621.63,Tasa de Uso,5.96,5.96
16,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,COMERCIAL,11331.05,3394.88,3394.88,Tasa de Uso,3.52,3.52
17,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,OFICIAL,7139.92,2139.18,2139.18,Tasa de Uso,5.59,5.59
18,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,INDUSTRIAL,9424.69,2823.72,2823.72,Tasa de Uso,4.65,4.65
19,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,ESPECIAL,7139.92,2139.18,2139.18,Tasa de Uso,0.00,0.00
20,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,BAJO - BAJO,7065.60,1554.43,2391.44,Tasa de Uso,2.59,3.98
21,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,BAJO,7065.60,1793.58,2391.44,Tasa de Uso,2.99,3.98
22,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO - BAJO,7065.60,2271.86,2391.44,Tasa de Uso,3.78,3.98
23,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO,7065.60,2391.44,2391.44,Tasa de Uso,3.98,3.98
24,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO - ALTO,10598.40,3587.16,3587.16,Tasa de Uso,5.97,5.97
25,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,ALTO,11304.96,3826.30,3826.30,Tasa de Uso,6.37,6.37
26,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,COMERCIAL,10598.40,3587.16,3587.16,Tasa de Uso,3.98,3.98
27,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,OFICIAL,7065.60,2391.44,2391.44,Tasa de Uso,5.97,5.97
28,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,INDUSTRIAL,9185.28,3108.87,3108.87,Tasa de Uso,5.17,5.17
29,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,ESPECIAL*,7065.60,2391.44,2391.44,Tasa de Uso,0.00,0.00
30,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,BAJO - BAJO,2176.20,736.56,2391.44,Tasa de Uso,1.23,3.98
31,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,BAJO,4352.41,1473.13,2391.44,Tasa de Uso,2.45,3.98
32,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO - BAJO,6168.27,2087.72,2391.44,Tasa de Uso,3.47,3.98
33,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO,7065.60,2391.44,2391.44,Tasa de Uso,3.98,3.98
34,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,MEDIO - ALTO,11213.11,3795.21,3795.21,Tasa de Uso,6.32,6.32
35,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,ALTO,11962.06,4048.70,4048.70,Tasa de Uso,6.74,6.74
36,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,COMERCIAL,11213.11,3795.21,3795.21,Tasa de Uso,3.98,3.98
37,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,OFICIAL,7065.60,2391.44,2391.44,Tasa de Uso,6.32,6.32
38,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,INDUSTRIAL,9326.59,3156.70,3156.70,Tasa de Uso,5.25,5.25
39,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,ESPECIAL,7065.60,2391.44,2391.44,Tasa de Uso,0.00,0.00
40,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,BAJO - BAJO,4911.38,1338.29,2058.90,Tasa Retributiva,45.97,70.72
41,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,BAJO,4911.38,1544.18,2058.90,Tasa Retributiva,53.04,70.72
42,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,MEDIO - BAJO,4911.38,1955.96,2058.90,Tasa Retributiva,67.18,70.72
43,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,MEDIO,4911.38,2058.90,2058.90,Tasa Retributiva,70.72,70.72
44,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,MEDIO - ALTO,7367.07,3088.35,3088.35,Tasa Retributiva,106.08,106.08
45,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,ALTO,7858.21,3294.24,3294.24,Tasa Retributiva,113.15,113.15
46,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,COMERCIAL,7367.07,3088.35,3088.35,Tasa Retributiva,106.08,106.08
47,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,OFICIAL,4911.38,2058.90,2058.90,Tasa Retributiva,70.72,70.72
48,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,INDUSTRIAL,6384.79,2676.57,2676.57,Tasa Retributiva,91.94,91.94
49,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,ESPECIAL*,4911.38,2058.90,2058.90,Tasa Retributiva,0.00,0.00
50,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,BAJO - BAJO,4584.51,1454.58,2237.81,Tasa Retributiva,50.06,77.02
51,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,BAJO,4584.51,1678.36,2237.81,Tasa Retributiva,57.77,77.02
52,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,MEDIO - BAJO,4584.51,2125.92,2237.81,Tasa Retributiva,73.17,77.02
53,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,MEDIO,4584.51,2237.81,2237.81,Tasa Retributiva,77.02,77.02
54,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,MEDIO - ALTO,6876.77,3356.72,3356.72,Tasa Retributiva,115.53,115.53
55,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,ALTO,7335.22,3580.50,3580.50,Tasa Retributiva,123.23,123.23
56,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,COMERCIAL,6876.77,3356.72,3356.72,Tasa Retributiva,115.53,115.53
57,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,OFICIAL,4584.51,2237.81,2237.81,Tasa Retributiva,77.02,77.02
58,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,INDUSTRIAL,5959.87,2909.16,2909.16,Tasa Retributiva,100.13,100.13
59,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,ESPECIAL*,4584.51,2237.81,2237.81,Tasa Retributiva,0.00,0.00

In [17]:
promediodecargofijo=tarifas['CARGO FIJO'].mean()
promediodecargofijo
#Esta linea de codigo nos dice cual es el promedio de la columna de cargos fijos, segun servicios; acueducto y alcantarillado

7301.3414999999995

In [21]:
filtro1 = tarifas[tarifas['SECTOR RESIDENCIAL'] == 'COMERCIAL']
filtro1
#Esta linea de codigo nos permite filtrar los sectores residenciales seleccionados como comerciales

,CIUDAD,PERIODO,SERVICIO,SECTOR RESIDENCIAL,CARGO FIJO,CARGO POR CONSUMO 0-16,CARGO POR CONSUMO >-17,TIPO DE TASA,TASA 0-16,TASA >-17
6,CARTAGO,PRIMER SEMESTE,ACUEDUCTO,COMERCIAL,10709.88,3208.77,3208.77,Tasa de Uso,3.52,3.52
16,PUERTO CALDAS,PRIMER SEMESTE,ACUEDUCTO,COMERCIAL,11331.05,3394.88,3394.88,Tasa de Uso,3.52,3.52
26,CARTAGO,SEGUNDO SEMESTRE,ACUEDUCTO,COMERCIAL,10598.40,3587.16,3587.16,Tasa de Uso,3.98,3.98
36,PUERTO CALDAS,SEGUNDO SEMESTRE,ACUEDUCTO,COMERCIAL,11213.11,3795.21,3795.21,Tasa de Uso,3.98,3.98
46,CARTAGO,PRIMER SEMESTE,ALCANTARILLADO,COMERCIAL,7367.07,3088.35,3088.35,Tasa Retributiva,106.08,106.08
56,CARTAGO,SEGUNDO SEMESTRE,ALCANTARILLADO,COMERCIAL,6876.77,3356.72,3356.72,Tasa Retributiva,115.53,115.53

In [31]:
tarifas['sen'] = np.sin(tarifas['CARGO FIJO'])
tarifas['sen']

0     0.795663
1     0.795663
2     0.795663
3     0.795663
4    -0.189491
5     0.861954
6    -0.189491
7     0.795663
8     0.997920
9     0.795663
10   -0.014857
11   -0.039705
12    0.479579
13    0.795663
14    0.624664
15   -0.824054
16    0.624664
17    0.795663
18   -0.087847
19    0.795663
20   -0.157464
21   -0.157464
22   -0.157464
23   -0.157464
24   -0.972004
25    0.998130
26   -0.972004
27   -0.157464
28   -0.672010
29   -0.157464
30    0.797843
31   -0.964667
32   -0.969607
33   -0.157464
34   -0.693128
35   -0.902192
36   -0.693128
37   -0.157464
38    0.716372
39   -0.157464
40   -0.877528
41   -0.877528
42   -0.877528
43   -0.877528
44   -0.035220
45   -0.885130
46   -0.035220
47   -0.877528
48    0.878984
49   -0.877528
50   -0.799414
51   -0.799414
52   -0.799414
53   -0.799414
54    0.175407
55    0.388355
56    0.175407
57   -0.799414
58   -0.265513
59   -0.799414
Name: sen, dtype: float64

In [32]:
tarifas['cos'] = np.cos(tarifas['CARGO FIJO'])
tarifas['cos']

0    -0.605739
1    -0.605739
2    -0.605739
3    -0.605739
4    -0.981882
5     0.506986
6    -0.981882
7    -0.605739
8    -0.064460
9    -0.605739
10    0.999890
11    0.999211
12    0.877499
13   -0.605739
14   -0.780893
15    0.566511
16   -0.780893
17   -0.605739
18    0.996134
19   -0.605739
20   -0.987525
21   -0.987525
22   -0.987525
23   -0.987525
24    0.234966
25    0.061126
26    0.234966
27   -0.987525
28    0.740542
29   -0.987525
30   -0.602865
31   -0.263474
32   -0.244666
33   -0.987525
34   -0.720815
35    0.431335
36   -0.720815
37   -0.987525
38   -0.697719
39   -0.987525
40   -0.479525
41   -0.479525
42   -0.479525
43   -0.479525
44   -0.999380
45   -0.465344
46   -0.999380
47   -0.479525
48    0.476851
49   -0.479525
50   -0.600781
51   -0.600781
52   -0.600781
53   -0.600781
54   -0.984496
55   -0.921510
56   -0.984496
57   -0.600781
58   -0.964107
59   -0.600781
Name: cos, dtype: float64

In [33]:
tarifas['raiz'] = np.sqrt(tarifas['CARGO FIJO'])
tarifas['raiz']

0      84.498047
1      84.498047
2      84.498047
3      84.498047
4     103.488550
5     106.882506
6     103.488550
7      84.498047
8      96.342618
9      84.498047
10     46.894563
11     66.318851
12     78.952011
13     84.498047
14    106.447405
15    109.944895
16    106.447405
17     84.498047
18     97.080843
19     84.498047
20     84.057123
21     84.057123
22     84.057123
23     84.057123
24    102.948531
25    106.324785
26    102.948531
27     84.057123
28     95.839866
29     84.057123
30     46.649759
31     65.972797
32     78.538335
33     84.057123
34    105.891973
35    109.371203
36    105.891973
37     84.057123
38     96.574272
39     84.057123
40     70.081239
41     70.081239
42     70.081239
43     70.081239
44     85.831638
45     88.646545
46     85.831638
47     70.081239
48     79.904881
49     70.081239
50     67.709010
51     67.709010
52     67.709010
53     67.709010
54     82.926293
55     85.645899
56     82.926293
57     67.709010
58     77.200194
59     67.709010
Name: raiz, dtype: float64

In [35]:
tarifas['sumaacumuladacargofijo'] =tarifas['CARGO FIJO'].cumsum()
tarifas['sumaacumuladacargofijo']

0       7139.92
1      14279.84
2      21419.76
3      28559.68
4      39269.56
5      50693.43
6      61403.31
7      68543.23
8      77825.13
9      84965.05
10     87164.15
11     91562.34
12     97795.76
13    104935.68
14    116266.73
15    128354.61
16    139685.66
17    146825.58
18    156250.27
19    163390.19
20    170455.79
21    177521.39
22    184586.99
23    191652.59
24    202250.99
25    213555.95
26    224154.35
27    231219.95
28    240405.23
29    247470.83
30    249647.03
31    253999.44
32    260167.71
33    267233.31
34    278446.42
35    290408.48
36    301621.59
37    308687.19
38    318013.78
39    325079.38
40    329990.76
41    334902.14
42    339813.52
43    344724.90
44    352091.97
45    359950.18
46    367317.25
47    372228.63
48    378613.42
49    383524.80
50    388109.31
51    392693.82
52    397278.33
53    401862.84
54    408739.61
55    416074.83
56    422951.60
57    427536.11
58    433495.98
59    438080.49
Name: sumaacumuladacargofijo, dtype: float64

In [36]:
tarifas['DESVIACION'] =tarifas['CARGO FIJO'].std()
tarifas['DESVIACION']

0     2457.296051
1     2457.296051
2     2457.296051
3     2457.296051
4     2457.296051
5     2457.296051
6     2457.296051
7     2457.296051
8     2457.296051
9     2457.296051
10    2457.296051
11    2457.296051
12    2457.296051
13    2457.296051
14    2457.296051
15    2457.296051
16    2457.296051
17    2457.296051
18    2457.296051
19    2457.296051
20    2457.296051
21    2457.296051
22    2457.296051
23    2457.296051
24    2457.296051
25    2457.296051
26    2457.296051
27    2457.296051
28    2457.296051
29    2457.296051
30    2457.296051
31    2457.296051
32    2457.296051
33    2457.296051
34    2457.296051
35    2457.296051
36    2457.296051
37    2457.296051
38    2457.296051
39    2457.296051
40    2457.296051
41    2457.296051
42    2457.296051
43    2457.296051
44    2457.296051
45    2457.296051
46    2457.296051
47    2457.296051
48    2457.296051
49    2457.296051
50    2457.296051
51    2457.296051
52    2457.296051
53    2457.296051
54    2457.296051
55    2457.296051
56    2457.296051
57    2457.296051
58    2457.296051
59    2457.296051
Name: DESVIACION, dtype: float64

In [37]:
tarifas['varianza'] =tarifas['CARGO FIJO'].var()
tarifas['varianza']

0     6.038304e+06
1     6.038304e+06
2     6.038304e+06
3     6.038304e+06
4     6.038304e+06
5     6.038304e+06
6     6.038304e+06
7     6.038304e+06
8     6.038304e+06
9     6.038304e+06
10    6.038304e+06
11    6.038304e+06
12    6.038304e+06
13    6.038304e+06
14    6.038304e+06
15    6.038304e+06
16    6.038304e+06
17    6.038304e+06
18    6.038304e+06
19    6.038304e+06
20    6.038304e+06
21    6.038304e+06
22    6.038304e+06
23    6.038304e+06
24    6.038304e+06
25    6.038304e+06
26    6.038304e+06
27    6.038304e+06
28    6.038304e+06
29    6.038304e+06
30    6.038304e+06
31    6.038304e+06
32    6.038304e+06
33    6.038304e+06
34    6.038304e+06
35    6.038304e+06
36    6.038304e+06
37    6.038304e+06
38    6.038304e+06
39    6.038304e+06
40    6.038304e+06
41    6.038304e+06
42    6.038304e+06
43    6.038304e+06
44    6.038304e+06
45    6.038304e+06
46    6.038304e+06
47    6.038304e+06
48    6.038304e+06
49    6.038304e+06
50    6.038304e+06
51    6.038304e+06
52    6.038304e+06
53    6.038304e+06
54    6.038304e+06
55    6.038304e+06
56    6.038304e+06
57    6.038304e+06
58    6.038304e+06
59    6.038304e+06
Name: varianza, dtype: float64

In [38]:
tarifas['minimo'] =tarifas['CARGO FIJO'].min()
tarifas['minimo']

0     2176.2
1     2176.2
2     2176.2
3     2176.2
4     2176.2
5     2176.2
6     2176.2
7     2176.2
8     2176.2
9     2176.2
10    2176.2
11    2176.2
12    2176.2
13    2176.2
14    2176.2
15    2176.2
16    2176.2
17    2176.2
18    2176.2
19    2176.2
20    2176.2
21    2176.2
22    2176.2
23    2176.2
24    2176.2
25    2176.2
26    2176.2
27    2176.2
28    2176.2
29    2176.2
30    2176.2
31    2176.2
32    2176.2
33    2176.2
34    2176.2
35    2176.2
36    2176.2
37    2176.2
38    2176.2
39    2176.2
40    2176.2
41    2176.2
42    2176.2
43    2176.2
44    2176.2
45    2176.2
46    2176.2
47    2176.2
48    2176.2
49    2176.2
50    2176.2
51    2176.2
52    2176.2
53    2176.2
54    2176.2
55    2176.2
56    2176.2
57    2176.2
58    2176.2
59    2176.2
Name: minimo, dtype: float64

In [39]:
tarifas['maximo'] =tarifas['CARGO FIJO'].max()
tarifas['maximo']

0     12087.88
1     12087.88
2     12087.88
3     12087.88
4     12087.88
5     12087.88
6     12087.88
7     12087.88
8     12087.88
9     12087.88
10    12087.88
11    12087.88
12    12087.88
13    12087.88
14    12087.88
15    12087.88
16    12087.88
17    12087.88
18    12087.88
19    12087.88
20    12087.88
21    12087.88
22    12087.88
23    12087.88
24    12087.88
25    12087.88
26    12087.88
27    12087.88
28    12087.88
29    12087.88
30    12087.88
31    12087.88
32    12087.88
33    12087.88
34    12087.88
35    12087.88
36    12087.88
37    12087.88
38    12087.88
39    12087.88
40    12087.88
41    12087.88
42    12087.88
43    12087.88
44    12087.88
45    12087.88
46    12087.88
47    12087.88
48    12087.88
49    12087.88
50    12087.88
51    12087.88
52    12087.88
53    12087.88
54    12087.88
55    12087.88
56    12087.88
57    12087.88
58    12087.88
59    12087.88
Name: maximo, dtype: float64